source "https://rubygems.org"

ruby "3.2.8"

gem "rails", "~> 7.1.5", ">= 7.1.5.1"

gem "pg", "~> 1.1"

gem "puma", ">= 5.0"

gem 'http'

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bootsnap", require: false

gem 'rack-cors'

gem 'dotenv-rails'


group :development, :test do

  gem "debug", platforms: %i[ mri windows ]
end

group :development do

end

